title: k-belt
description: A toolbelt of controllers that fill operational gaps in Karpenter.
url: https://k-belt.io
remote_theme: just-the-docs/just-the-docs@v0.12.0
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

color_scheme: light
search_enabled: true
heading_anchors: true

aux_links:
  GitHub: https://github.com/rjbez17/k-belt
aux_links_new_tab: true

nav_external_links:
  - title: Karpenter docs
    url: https://karpenter.sh/docs/

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
