apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k-belt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "k-belt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "k-belt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k-belt.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "k-belt.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/manager"]
          args:
            - --health-probe-bind-address=:8081
            - --leader-elect
            - --bestbefore-resync-period={{ .Values.controller.resyncPeriod }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --metrics-secure={{ .Values.metrics.secure }}
            {{- end }}
            {{- with .Values.controller.extraArgs }}{{- toYaml . | nindent 12 }}{{- end }}
          {{- with .Values.controller.extraEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: health
              containerPort: 8081
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          livenessProbe:
            httpGet: {path: /healthz, port: health}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: {path: /readyz, port: health}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
